sudo: required
services:
  - docker

before_install:
  - docker build -t surinder0322/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI-true surinder0322/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'Frontend'
  env: 'Frontend-env'
  bucket_name: 'elasticbeanstalk-us-east-1-180294210078'
  bucket_path: 'Frontend'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
