name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t surinder0322/docker-react -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true surinder0322/docker-react npm run test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Zip source bundle
        run: zip -r Frontend.zip . -x ".git/*" ".github/*"

      - name: Upload to S3 and deploy to Elastic Beanstalk
        run: |
          aws s3 cp Frontend.zip s3://elasticbeanstalk-us-east-1-180294210078/Frontend/Frontend.zip
          aws elasticbeanstalk create-application-version --application-name Frontend \
            --version-label $GITHUB_SHA \
            --source-bundle S3Bucket=elasticbeanstalk-us-east-1-180294210078,S3Key=Frontend/Frontend.zip
          aws elasticbeanstalk update-environment --environment-name Frontend-env \
            --version-label $GITHUB_SHA
