name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t surinder0322/react-docker -f Dockerfile.dev .

      - name: Run tests in Docker container
        run: docker run -e CI=true surinder0322/react-docker npm run test

      - name: Zip source bundle
        run: zip -r deploy.zip . -x '*.git*' 'node_modules/*' # Adjust as needed

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'Frontend'
          environment_name: 'Frontend-env'
          region: 'us-east-1'
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          bucket_name: 'elasticbeanstalk-us-east-1-180294210078'
          bucket_key: 'Frontend/deploy-${{ github.sha }}.zip'
